---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  driver_config:
  	box: win2k8r2
  	box_url: https://dl.dropboxusercontent.com/u/2105139/vagrant/win2k8r2.box


suites:
  - name: default
    run_list:
      - recipe[xm-demo-cookbook::default]
    attributes:
