---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: win2k8r2
    driver_config:
    box: win2k8r2
    box_url: https://dl.dropboxusercontent.com/u/2105139/vagrant/win2k8r2.box

suites:
  - name: default
    run_list:
      - recipe[xm-demo-cookbook::default]
    attributes: {}